title: Sahil's Blog
description: >
  Code. Travel. Random Writings
url: "/"
paginate:	5 # The number of posts to show per page on your homepage
name: "Sahil Chanchad"
email: 'chanchadsahil7@gmail.com'
markdown: kramdown
# twitter_username:
# twitter_image:
permalink: none
kramdown:
  parse_block_html: true
plugins: [jekyll-paginate]
gems:
  - jekyll-paginate
  - jekyll-compose
  - jekyll-sass-converter
  - jekyll-textile-converter
long_description: >
  I write about Travel, Technology, Poems and some time random stuff.
real_url: https://chanchadsahil7.github.io